// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/custom_handler.dart';
import 'api/error.dart';
import 'api/pub_structs.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ErrorPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MyCustomAsyncRuntimePtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ThreadPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_WalletMethodPtr => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected Error dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(dynamic raw);

@protected MyCustomAsyncRuntime dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(dynamic raw);

@protected Thread dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(dynamic raw);

@protected WalletMethod dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(dynamic raw);

@protected FutureOr<String?> Function(DartMethod) dco_decode_DartFn_Inputs_dart_method_Output_opt_String_AnyhowException(dynamic raw);

@protected Object dco_decode_DartOpaque(dynamic raw);

@protected Error dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(dynamic raw);

@protected MyCustomAsyncRuntime dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(dynamic raw);

@protected Thread dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(dynamic raw);

@protected WalletMethod dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected DartMethod dco_decode_box_autoadd_dart_method(dynamic raw);

@protected KeyPress dco_decode_box_autoadd_key_press(dynamic raw);

@protected PageName dco_decode_box_autoadd_page_name(dynamic raw);

@protected Profile dco_decode_box_autoadd_profile(dynamic raw);

@protected ShorthandTransaction dco_decode_box_autoadd_shorthand_transaction(dynamic raw);

@protected DartMethod dco_decode_dart_method(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_isize(dynamic raw);

@protected KeyPress dco_decode_key_press(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected KeyPress? dco_decode_opt_box_autoadd_key_press(dynamic raw);

@protected PageName dco_decode_page_name(dynamic raw);

@protected Platform dco_decode_platform(dynamic raw);

@protected Profile dco_decode_profile(dynamic raw);

@protected ShorthandTransaction dco_decode_shorthand_transaction(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected Error sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(SseDeserializer deserializer);

@protected MyCustomAsyncRuntime sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(SseDeserializer deserializer);

@protected Thread sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(SseDeserializer deserializer);

@protected WalletMethod sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(SseDeserializer deserializer);

@protected Object sse_decode_DartOpaque(SseDeserializer deserializer);

@protected Error sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(SseDeserializer deserializer);

@protected MyCustomAsyncRuntime sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(SseDeserializer deserializer);

@protected Thread sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(SseDeserializer deserializer);

@protected WalletMethod sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected DartMethod sse_decode_box_autoadd_dart_method(SseDeserializer deserializer);

@protected KeyPress sse_decode_box_autoadd_key_press(SseDeserializer deserializer);

@protected PageName sse_decode_box_autoadd_page_name(SseDeserializer deserializer);

@protected Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer);

@protected ShorthandTransaction sse_decode_box_autoadd_shorthand_transaction(SseDeserializer deserializer);

@protected DartMethod sse_decode_dart_method(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

@protected KeyPress sse_decode_key_press(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected KeyPress? sse_decode_opt_box_autoadd_key_press(SseDeserializer deserializer);

@protected PageName sse_decode_page_name(SseDeserializer deserializer);

@protected Platform sse_decode_platform(SseDeserializer deserializer);

@protected Profile sse_decode_profile(SseDeserializer deserializer);

@protected ShorthandTransaction sse_decode_shorthand_transaction(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(Error self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(MyCustomAsyncRuntime self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(Thread self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(WalletMethod self, SseSerializer serializer);

@protected void sse_encode_DartFn_Inputs_dart_method_Output_opt_String_AnyhowException(FutureOr<String?> Function(DartMethod) self, SseSerializer serializer);

@protected void sse_encode_DartOpaque(Object self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(Error self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(MyCustomAsyncRuntime self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(Thread self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(WalletMethod self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_dart_method(DartMethod self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_key_press(KeyPress self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_page_name(PageName self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_shorthand_transaction(ShorthandTransaction self, SseSerializer serializer);

@protected void sse_encode_dart_method(DartMethod self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_key_press(KeyPress self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_key_press(KeyPress? self, SseSerializer serializer);

@protected void sse_encode_page_name(PageName self, SseSerializer serializer);

@protected void sse_encode_platform(Platform self, SseSerializer serializer);

@protected void sse_encode_profile(Profile self, SseSerializer serializer);

@protected void sse_encode_shorthand_transaction(ShorthandTransaction self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(ptr);

void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(int ptr) => wasmModule.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(ptr);

void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(int ptr) => wasmModule.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(ptr);
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerError(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMyCustomAsyncRuntime(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerThread(int ptr);

external void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(int ptr);

external void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletMethod(int ptr);
        }
        