name: flow_messages
description: "Messages Screens"
version: 0.1.0
homepage:


environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - ../assets/icons/
    - ../assets/images/
