// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_bytes`
// These functions are ignored because they have generic arguments: `new`
// These types are ignored because they are not used by any `pub` functions: `PriceRes`, `Price`, `SpotRes`, `Spot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PriceGetter>>
abstract class PriceGetter implements RustOpaqueInterface {
  Future<void> fetchPrice();

  Future<double> get_({BigInt? timestamp});
}
