// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProtocolDefinition>>
@sealed
class ProtocolDefinition extends RustOpaque {
  // Not to be used by end users
  ProtocolDefinition.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ProtocolDefinition.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ProtocolDefinition,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ProtocolDefinition,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_ProtocolDefinitionPtr,
  );
}

class ProfileProtocol {
  const ProfileProtocol();

  static Future<ProtocolDefinition> get() =>
      RustLib.instance.api.crateApiProtocolsProfileProtocolGet();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileProtocol && runtimeType == other.runtimeType;
}

class SocialProtocol {
  const SocialProtocol();

  static Future<ProtocolDefinition> get() =>
      RustLib.instance.api.crateApiProtocolsSocialProtocolGet();

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SocialProtocol && runtimeType == other.runtimeType;
}
