// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

enum Field {
  identity,
  legacySeed,
  descriptorSet,
  internet,
  platform,
  profile,
  address,
  amount,
  priority,
  amountErr,
  amountBtc,
  decimals,
  inputValidation,
  price,
  path,
  balance,
  currentConversation,
  conversations,
  users,
  transactions,
  currentTx,
  currentRawTx,
  ;

  Future<Uint8List> intoBytes() =>
      RustLib.instance.api.crateApiPubStructsFieldIntoBytes(
        that: this,
      );
}

enum PageName {
  bitcoinHome,
  receive,
  send,
  scanQr,
  amount,
  speed,
  confirmTransaction,
  success,
  viewTransaction,
  messagesHome,
  exchange,
  myProfile,
  convoInfo,
  chooseRecipient,
  test,
  ;
}
