// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'pub_structs.freezed.dart';

// These types are ignored because they are not used by any `pub` functions: `KeyPress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`

@freezed
sealed class PageName with _$PageName {
  const PageName._();

  const factory PageName.bitcoinHome() = PageName_BitcoinHome;
  const factory PageName.speed(
    String field0,
    BigInt field1,
  ) = PageName_Speed;
  const factory PageName.receive() = PageName_Receive;
  const factory PageName.viewTransaction(
    String field0,
  ) = PageName_ViewTransaction;
  const factory PageName.myProfile() = PageName_MyProfile;
  const factory PageName.test() = PageName_Test;
}

enum Platform {
  mac,
  linux,
  windows,
  ios,
  android,
  fuchsia,
  ;

  bool isDesktop() => RustLib.instance.api.crateApiPubStructsPlatformIsDesktop(
        that: this,
      );
}

@freezed
sealed class Thread with _$Thread {
  const Thread._();

  const factory Thread.wallet(
    WalletMethod field0,
  ) = Thread_Wallet;
}

@freezed
sealed class WalletMethod with _$WalletMethod {
  const WalletMethod._();

  const factory WalletMethod.getNewAddress() = WalletMethod_GetNewAddress;
  const factory WalletMethod.getFees(
    String field0,
    BigInt field1,
    double field2,
  ) = WalletMethod_GetFees;
}
