// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_details`, `get_descriptors`, `get_price`, `invoke`
// These types are ignored because they are not used by any `pub` functions: `DartCommand`, `DartState`, `Data`, `DescriptorSet`, `PriceRes`, `Price`, `RustCommand`, `RustResponse`, `SpotRes`, `Spot`, `Transaction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `default`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<String> rustStart(
        {required String path,
        required FutureOr<String> Function(String) callback,
        required FutureOr<String> Function(String) callback3,
        required FutureOr<String> Function(String) callback1}) =>
    RustLib.instance.api.crateApiSimpleRustStart(
        path: path,
        callback: callback,
        callback3: callback3,
        callback1: callback1);
