// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.37.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `DartCommand` is not used by any `pub` functions, thus it is ignored.
// The type `DescriptorSet` is not used by any `pub` functions, thus it is ignored.
// The type `Price` is not used by any `pub` functions, thus it is ignored.
// The type `PriceRes` is not used by any `pub` functions, thus it is ignored.
// The type `RustCommand` is not used by any `pub` functions, thus it is ignored.
// The type `RustResponse` is not used by any `pub` functions, thus it is ignored.
// The functions `handleError`, `invoke`, `start_rust`, `fmt`, `fmt`, `fmt`, `fmt` are not `pub`, thus are ignored.

Future<String> rustStart(
        {required String path,
        required FutureOr<String> Function(String) dartCallback}) =>
    RustLib.instance.api
        .crateApiSimpleRustStart(path: path, dartCallback: dartCallback);
